// Strategies data — structured from the xlsx bible.
// Each strategy: name, tagline, timeframe, when, entry, exit, sl, pros, cons, notes.

const BibleStrategies = [
  {
    id: "vwap",
    name: "VWAP Pullback",
    tagline: "Option buying only when strike > SuperTrend > VWAP.",
    timeframe: "3 / 5 min",
    when: [
      "Market has direction (not pure range).",
      "Strike price is above BOTH VWAP and SuperTrend.",
      "VWAP acts as magnet — pullback to VWAP is the entry.",
    ],
    entry: [
      "Watch ATM/ITM CE & PE simultaneously.",
      "Whichever side is above VWAP and SuperTrend — that's your side.",
      "Buy on pullback into VWAP with a green candle confirmation.",
    ],
    exit: [
      "Scenario 1: price comes back to VWAP with no follow-through → exit CTC (close-to-cost). No hesitation.",
      "Scenario 2: price moves away with momentum → trail on 20/50/200 EMA, SuperTrend, Camarilla.",
      "Can re-enter on the next VWAP touch the same day.",
    ],
    sl: "20-25 points on the option premium. Hard stop in system.",
    pros: ["4-5 trades/day possible", "2-3 give 150-200 pts", "Clear invalidation (VWAP break)"],
    cons: ["Chop kills it", "Needs practice live — post-market looks easier than it is"],
    notes: [
      "Never buy when strike is below VWAP — that's the seller's zone.",
      "50k-volume candle near VWAP = large player arrival.",
    ],
    diagram: "vwap",
  },
  {
    id: "oh",
    name: "O = H / O = L",
    tagline: "The day's opening equals the high (or low). Trap the big-player bias.",
    timeframe: "1 / 3 min, before 9:45 AM",
    when: [
      "Within the first 15 minutes of market open.",
      "ATM / ITM first — not OTM.",
      "Cross-check F&O data, price action, open interest.",
    ],
    entry: [
      "Identify CE / PE side where O=H or O=L (OI Pulse).",
      "Wait — do NOT buy on sight of O=H.",
      "Enter only on supportive momentum + VWAP confirmation.",
      "Pick the strike whose premium is closest to target (not the cheapest).",
    ],
    exit: [
      "Target = day's high / low.",
      "Always trail once in profit.",
      "Avoid setup if Δpremium vs ΔOI crosses the 50% barrier.",
    ],
    sl: "Premium stop below the setup candle. ~15-20 pts.",
    pros: ["Triggers almost every day", "Early clarity on big-player bias", "~1% achievable"],
    cons: ["Fails in range days (O=H both sides)", "OTM strikes trap beginners"],
    notes: [
      "O=H on both CE and PE → range-bound day. Scalp only.",
      "O=H first touch is best for ITM strikes.",
    ],
    diagram: "oh",
  },
  {
    id: "2candle",
    name: "2-Candle Theory",
    tagline: "Intraday bias read from two consecutive candles.",
    timeframe: "3 min, 10:15 AM – 2:30 PM",
    when: [
      "Outside opening volatility.",
      "Before the settlement noise of the last hour.",
      "Market has direction, not pure chop.",
    ],
    entry: [
      "Bullish: two green candles, 2nd closes above 1st high, stoch > 40, price above VWAP.",
      "Bearish: two red candles, 2nd closes below 1st low, stoch < 40, price below VWAP.",
      "Enter on break of the 2nd candle's high/low.",
    ],
    exit: [
      "Fixed 1% target, or trail on 20 EMA.",
      "Exit if a counter-candle of equal size prints.",
    ],
    sl: "Below (or above) the 1st candle — typically 20 pts.",
    pros: ["Simple, rule-based", "Works every day between 10:15-2:30", "Good for scalping"],
    cons: ["Whipsaw inside ranges", "Needs stoch + VWAP confirmation or false signals increase"],
    notes: ["3-min timeframe only. Don't force it on 1-min."],
    diagram: "twocandle",
  },
  {
    id: "wm",
    name: "W / M Breakout",
    tagline: "Classic double-bottom / double-top on line chart.",
    timeframe: "3 / 5 min",
    when: [
      "Pattern visible on line chart (remove wicks for clarity).",
      "Ideally near a key level — VWAP / PDH / PDL / 200 EMA.",
    ],
    entry: [
      "W pattern → buy CE on neckline breakout.",
      "M pattern → buy PE on neckline breakdown.",
      "Breakout candle must be wide-body with volume.",
    ],
    exit: [
      "Attention shifts to VWAP, SuperTrend, EMA, prior trendline, PDH/PDL, Camarilla.",
      "Exit at the nearest dynamic resistance/support.",
    ],
    sl: "Below the W's second bottom / above the M's second top.",
    pros: ["Works on any chart", "Strong if aligned with VWAP break", "Clear invalidation"],
    cons: ["Needs a clean pattern", "Late entries give poor RR"],
    notes: ["Combine with trendline break for highest probability."],
    diagram: "wm",
  },
  {
    id: "tl",
    name: "Trend-Line Breakout",
    tagline: "Draw the cleanest trendline. Trade the break.",
    timeframe: "3 / 5 min, live",
    when: [
      "Clear trendline forms (3+ touches).",
      "Works best near day's high / low.",
    ],
    entry: [
      "Wait for a wide-body candle to break & close through the trendline.",
      "TL break + VWAP break = strong confluence.",
    ],
    exit: [
      "Exit at next TL, EMA, SuperTrend, Camarilla, PDH/PDL.",
      "Bottom→up TL breaks down → good fall.",
      "Top→down TL breaks up → good spike.",
    ],
    sl: "Inside the trendline, 20-25 pts.",
    pros: ["Visual, intuitive", "High-probability at extremes", "Good RR"],
    cons: ["Subjective drawing", "Fakeouts on low-volume bars"],
    notes: ["Mark day's high/low — rejection or breakout gives the best momentum zone."],
    diagram: "tl",
  },
  {
    id: "sr",
    name: "Support / Resistance Breakout",
    tagline: "Trade only between defined levels. Break of level = momentum.",
    timeframe: "5 / 15 min",
    when: [
      "S/R lines drawn from prior-day data (KResearch / Kal Ki Baat Aaj).",
      "Additional intraday S/R from 15-min high/low.",
    ],
    entry: [
      "No trades BETWEEN S and R.",
      "Break of R → CE to next R.",
      "Break of S → PE to next S.",
    ],
    exit: ["Target = next S/R.", "Trail at each intermediate EMA / Camarilla level."],
    sl: "Just inside the broken level.",
    pros: ["Disciplined — removes chop trades", "Clear targets", "High RR on break"],
    cons: ["Slow — few trades per day", "Misses intraday trends"],
    notes: ["15-min high/low expansion is a reliable momentum signal."],
    diagram: "sr",
  },
  {
    id: "10am",
    name: "10 AM BankNifty",
    tagline: "Trade the high/low of 9:15-10:00 range after the 10 AM candle.",
    timeframe: "5 min",
    when: [
      "After 10:00 AM, mark high & low of 9:15-10:00.",
      "Wait for the 10 AM candle to break one side.",
    ],
    entry: [
      "Break above 10 AM high → CE buy.",
      "Break below 10 AM low → PE buy.",
      "Must be a wide-body close, not a wick break.",
    ],
    exit: [
      "Target: 1.5× the opening range.",
      "Trail on 20 EMA after 1R.",
    ],
    sl: "Other side of the 10 AM candle.",
    pros: ["One trade per day max — low noise", "Clear rules", "Good on trend days"],
    cons: ["Nothing happens on range days", "Late start — misses early momentum"],
    notes: ["Stop trading this setup after 3 SLs or 50k loss."],
    diagram: "tenam",
  },
  {
    id: "2020",
    name: "20:20 (Zig-Zag)",
    tagline: "KingResearch's 20-point zig-zag model on BankNifty options.",
    timeframe: "5 min",
    when: [
      "Options premium shows a clear 20-pt swing structure.",
      "Trend is established.",
    ],
    entry: [
      "CE setup: premium makes higher-low after a 20-pt pullback; buy on break of swing high.",
      "PE setup: mirror.",
    ],
    exit: ["Exit at each 20-pt expansion or on swing break."],
    sl: "20 pts below entry swing-low (mirror for PE).",
    pros: ["Mechanical", "Works in trending intraday"],
    cons: ["Needs practice to read swings", "Fails in choppy markets"],
    notes: ["Pair with VWAP — only take trades on the VWAP-confirmed side."],
    diagram: "zigzag",
  },
  {
    id: "trafficlight",
    name: "Traffic Light",
    tagline: "Pair the first green & red candles. Trade the break.",
    timeframe: "1 min (switches to 5 min after 2 SLs)",
    when: [
      "Ignore the 9:15-9:16 candle.",
      "Identify the first RED-GREEN or GREEN-RED pair.",
      "Range of 200-300 pts between them.",
    ],
    entry: [
      "Mark high & low of the pair.",
      "Break above high → CE. Break below low → PE.",
    ],
    exit: ["Fixed target or opposite side of range."],
    sl: "60-80 pts if pair range > 100 pts. Position size accordingly.",
    pros: ["Very early signal", "Clear rules"],
    cons: ["1-min = high noise", "3 SLs = done for the day"],
    notes: [
      "Only 2 trades allowed on 1-min TF. Switch to 5-min after.",
      "3 consecutive SLs → stop. No exceptions.",
    ],
    diagram: "traffic",
  },
  {
    id: "123trend",
    name: "1-2-3 Trend",
    tagline: "Three-push structure. Enter on the third push-and-fail.",
    timeframe: "5 / 15 min",
    when: [
      "Strong trend day — higher-highs / lower-lows.",
      "Price makes three clear pushes in the same direction.",
    ],
    entry: [
      "Wait for push 3 to fail at a structural level.",
      "Enter on the first pullback candle against the trend.",
    ],
    exit: ["Back to the origin of push 1 or a prior S/R."],
    sl: "Beyond the high/low of push 3.",
    pros: ["High RR", "Clear invalidation"],
    cons: ["Few signals/week", "Needs patience"],
    notes: ["Often aligns with VWAP rejection."],
    diagram: "tl",
  },
];

window.BibleStrategies = BibleStrategies;
